CREATE SEQUENCE "HIBERNATE_SEQUENCE" START WITH 1;
CREATE MEMORY TABLE "ASSOCIATION_VALUE_ENTRY"(
    "ID" BIGINT NOT NULL,
    "ASSOCIATION_KEY" VARCHAR(255) NOT NULL,
    "ASSOCIATION_VALUE" VARCHAR(255),
    "SAGA_ID" VARCHAR(255) NOT NULL,
    "SAGA_TYPE" VARCHAR(255)
);
ALTER TABLE "ASSOCIATION_VALUE_ENTRY" ADD CONSTRAINT "CONSTRAINT_B" PRIMARY KEY("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ASSOCIATION_VALUE_ENTRY;
CREATE INDEX "IDXK45EQNXKGD8HPDN6XIXN8SGFT" ON "ASSOCIATION_VALUE_ENTRY"("SAGA_TYPE", "ASSOCIATION_KEY", "ASSOCIATION_VALUE");
CREATE INDEX "IDXGV5K1V2MH6FRXUY5C0HGBAU94" ON "ASSOCIATION_VALUE_ENTRY"("SAGA_ID", "SAGA_TYPE");
CREATE MEMORY TABLE "ORDER_ENTITY"(
    "ID" VARCHAR(255) NOT NULL,
    "DELIVERY_ADDRESS" VARCHAR(255),
    "ORDER_STATE" VARCHAR(255),
    "RESTAURANT_ID" VARCHAR(255),
    "USER_ID" VARCHAR(255)
);
ALTER TABLE "ORDER_ENTITY" ADD CONSTRAINT "CONSTRAINT_4" PRIMARY KEY("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ORDER_ENTITY;
CREATE MEMORY TABLE "ORDER_ENTITY_ORDER_LINE_ITEMS"(
    "ORDER_ENTITY_ID" VARCHAR(255) NOT NULL,
    "MENU_ITEM_ID" VARCHAR(255),
    "NAME" VARCHAR(255),
    "PRICE" DECIMAL(19, 2),
    "QUANTITY" INTEGER
);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ORDER_ENTITY_ORDER_LINE_ITEMS;
CREATE MEMORY TABLE "SAGA_ENTRY"(
    "SAGA_ID" VARCHAR(255) NOT NULL,
    "REVISION" VARCHAR(255),
    "SAGA_TYPE" VARCHAR(255),
    "SERIALIZED_SAGA" BLOB
);
ALTER TABLE "SAGA_ENTRY" ADD CONSTRAINT "CONSTRAINT_BD" PRIMARY KEY("SAGA_ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.SAGA_ENTRY;
CREATE MEMORY TABLE "TOKEN_ENTRY"(
    "PROCESSOR_NAME" VARCHAR(255) NOT NULL,
    "SEGMENT" INTEGER NOT NULL,
    "OWNER" VARCHAR(255),
    "TIMESTAMP" VARCHAR(255) NOT NULL,
    "TOKEN" BLOB,
    "TOKEN_TYPE" VARCHAR(255)
);
ALTER TABLE "TOKEN_ENTRY" ADD CONSTRAINT "CONSTRAINT_7" PRIMARY KEY("PROCESSOR_NAME", "SEGMENT");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TOKEN_ENTRY;
ALTER TABLE "ORDER_ENTITY_ORDER_LINE_ITEMS" ADD CONSTRAINT "FKGAJ6H7W5XQBRDP8NY5QWV27I9" FOREIGN KEY("ORDER_ENTITY_ID") REFERENCES "ORDER_ENTITY"("ID") NOCHECK;

CREATE MEMORY TABLE "DEAD_LETTER_ENTRY"(
    "DEAD_LETTER_ID" CHARACTER VARYING(255) NOT NULL,
    "CAUSE_MESSAGE" CHARACTER VARYING(255),
    "CAUSE_TYPE" CHARACTER VARYING(255),
    "DIAGNOSTICS" BINARY LARGE OBJECT,
    "ENQUEUED_AT" TIMESTAMP NOT NULL,
    "LAST_TOUCHED" TIMESTAMP,
    "AGGREGATE_IDENTIFIER" CHARACTER VARYING(255),
    "EVENT_IDENTIFIER" CHARACTER VARYING(255) NOT NULL,
    "MESSAGE_TYPE" CHARACTER VARYING(255) NOT NULL,
    "META_DATA" BINARY LARGE OBJECT,
    "PAYLOAD" BINARY LARGE OBJECT NOT NULL,
    "PAYLOAD_REVISION" CHARACTER VARYING(255),
    "PAYLOAD_TYPE" CHARACTER VARYING(255) NOT NULL,
    "SEQUENCE_NUMBER" BIGINT,
    "TIME_STAMP" CHARACTER VARYING(255) NOT NULL,
    "TOKEN" BINARY LARGE OBJECT,
    "TOKEN_TYPE" CHARACTER VARYING(255),
    "TYPE" CHARACTER VARYING(255),
    "PROCESSING_GROUP" CHARACTER VARYING(255) NOT NULL,
    "PROCESSING_STARTED" TIMESTAMP,
    "SEQUENCE_IDENTIFIER" CHARACTER VARYING(255) NOT NULL,
    "SEQUENCE_INDEX" BIGINT NOT NULL
);
ALTER TABLE "DEAD_LETTER_ENTRY" ADD CONSTRAINT "CONSTRAINT_5" PRIMARY KEY("DEAD_LETTER_ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.DEAD_LETTER_ENTRY;
CREATE INDEX "IDXE67WCX5FIQ9HL4Y4QKHLCJ9CG" ON "DEAD_LETTER_ENTRY"("PROCESSING_GROUP" NULLS FIRST);
CREATE INDEX "IDXRWUCPGS6SN93LDGOEH2Q9K6BN" ON "DEAD_LETTER_ENTRY"("PROCESSING_GROUP" NULLS FIRST, "SEQUENCE_IDENTIFIER" NULLS FIRST);

CREATE MEMORY TABLE "DOMAIN_EVENT_ENTRY"(
    "GLOBAL_INDEX" BIGINT NOT NULL,
    "EVENT_IDENTIFIER" CHARACTER VARYING(255) NOT NULL,
    "META_DATA" BINARY LARGE OBJECT,
    "PAYLOAD" BINARY LARGE OBJECT NOT NULL,
    "PAYLOAD_REVISION" CHARACTER VARYING(255),
    "PAYLOAD_TYPE" CHARACTER VARYING(255) NOT NULL,
    "TIME_STAMP" CHARACTER VARYING(255) NOT NULL,
    "AGGREGATE_IDENTIFIER" CHARACTER VARYING(255) NOT NULL,
    "SEQUENCE_NUMBER" BIGINT NOT NULL,
    "TYPE" CHARACTER VARYING(255)
);
ALTER TABLE "DOMAIN_EVENT_ENTRY" ADD CONSTRAINT "CONSTRAINT_8" PRIMARY KEY("GLOBAL_INDEX");


CREATE MEMORY TABLE "SNAPSHOT_EVENT_ENTRY"(
    "AGGREGATE_IDENTIFIER" CHARACTER VARYING(255) NOT NULL,
    "SEQUENCE_NUMBER" BIGINT NOT NULL,
    "TYPE" CHARACTER VARYING(255) NOT NULL,
    "EVENT_IDENTIFIER" CHARACTER VARYING(255) NOT NULL,
    "META_DATA" BINARY LARGE OBJECT,
    "PAYLOAD" BINARY LARGE OBJECT NOT NULL,
    "PAYLOAD_REVISION" CHARACTER VARYING(255),
    "PAYLOAD_TYPE" CHARACTER VARYING(255) NOT NULL,
    "TIME_STAMP" CHARACTER VARYING(255) NOT NULL
);
ALTER TABLE "SNAPSHOT_EVENT_ENTRY" ADD CONSTRAINT "CONSTRAINT_E" PRIMARY KEY("AGGREGATE_IDENTIFIER", "SEQUENCE_NUMBER", "TYPE");
