{
 "title": "Axon (Spring Boot) Applications Statistics",
 "description": "Dashboard for Spring Boot Statistics (micrometer-prometheus).",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": "label_values(app)" },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(jvm_classes_loaded_classes{app=\"$application\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Axon Commands", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Success Commands",
   "type": "singlestat",
   "description": "Total number of success commands",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (commandBus_successCounter_total{app=\"$application\", instance=~\"$instance\"}) by (app)"
    }
   ]
  },
  {
   "title": "Failed Commands",
   "type": "singlestat",
   "description": "Total number of failed commands",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(commandBus_failureCounter_total{app=\"$application\", instance=~\"$instance\"}) by (app)"
    }
   ]
  },
  {
   "title": "Processed Commands",
   "type": "singlestat",
   "description": "Total number of processed\n commands",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(commandBus_processedCounter_total{app=\"$application\", instance=~\"$instance\"}) by (app)"
    }
   ]
  },
  {
   "title": "Ingested Commands",
   "type": "singlestat",
   "description": "Total number of ingested\n commands",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(commandBus_ingestedCounter_total{app=\"$application\", instance=~\"$instance\"}) by (app)"
    }
   ]
  },
  {
   "title": "Ignored Commands",
   "type": "singlestat",
   "description": "Total number of ignored\n commands",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(commandBus_ignoredCounter_total{app=\"$application\", instance=~\"$instance\"}) by (app)"
    }
   ]
  },
  {
   "title": "Commands Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "sum(irate(commandBus_successCounter_total{app=\"$application\", instance=~\"$instance\"}[5m])) by (app)",
     "legendFormat": "Success commands"
    },
    {
     "expr": "sum(irate(commandBus_failureCounter_total{app=\"$application\", instance=~\"$instance\"}[5m])) by (app)",
     "legendFormat": "Failed commands"
    },
    {
     "expr": "sum(irate(commandBus_processedCounter_total{app=\"$application\", instance=~\"$instance\"}[5m])) by (app)",
     "legendFormat": "Processed commands"
    },
    {
     "expr": "sum(irate(commandBus_ingestedCounter_total{app=\"$application\", instance=~\"$instance\"}[5m])) by (app)",
     "legendFormat": "Ingested commands"
    },
    {
     "expr": "sum(irate(commandBus_ignoredCounter_total{app=\"$application\", instance=~\"$instance\"}[5m])) by (app)",
     "legendFormat": "Ignored commands"
    }
   ]
  },
  {
   "title": "Command Bus Capacity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(commandBus_capacity{app=\"$application\", instance=~\"$instance\"}) by (app)",
     "legendFormat": "Command bus"
    }
   ]
  },
  {
   "title": "Command Bus Latency",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(commandBus_allTimer_seconds{app=\"$application\", instance=~\"$instance\", quantile=\"0.5\"})by(app)",
     "legendFormat": "All timer (quantile=\"0.5\")"
    },
    {
     "expr": "avg(commandBus_allTimer_seconds{app=\"$application\", instance=~\"$instance\", quantile=\"0.75\"})by(app)",
     "legendFormat": "All timer (quantile=\"0.75\")"
    },
    {
     "expr": "avg(commandBus_allTimer_seconds{app=\"$application\", instance=~\"$instance\", quantile=\"0.999\"})by(app)",
     "legendFormat": "All timer (quantile=\"0.999\")"
    }
   ]
  },
  { "title": "Axon Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Success Events",
   "type": "singlestat",
   "description": "Total number of success events",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 16 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(eventStore_successCounter_total{app=\"$application\", instance=~\"$instance\"})by(app)"
    }
   ]
  },
  {
   "title": "Failed Events",
   "type": "singlestat",
   "description": "Total number of failed events",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 16 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(eventStore_failureCounter_total{app=\"$application\", instance=~\"$instance\"})by(app)"
    }
   ]
  },
  {
   "title": "Processed Events",
   "type": "singlestat",
   "description": "Total number of processed\n events",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 16 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(eventStore_processedCounter_total{app=\"$application\", instance=~\"$instance\"})by(app)"
    }
   ]
  },
  {
   "title": "Ingested Events",
   "type": "singlestat",
   "description": "Total number of ingested\n events",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 16 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(eventStore_ingestedCounter_total{app=\"$application\", instance=~\"$instance\"})by(app)"
    }
   ]
  },
  {
   "title": "Ignored Events",
   "type": "singlestat",
   "description": "Total number of ignored\n events",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 16 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(eventStore_ignoredCounter_total{app=\"$application\", instance=~\"$instance\"})by(app)"
    }
   ]
  },
  {
   "title": "Events Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "sum(irate(eventStore_successCounter_total{app=\"$application\", instance=~\"$instance\"}[5m]))by(app)",
     "legendFormat": "Success events"
    },
    {
     "expr": "sum(irate(eventStore_failureCounter_total{app=\"$application\", instance=~\"$instance\"}[5m]))by(app)",
     "legendFormat": "Failed events"
    },
    {
     "expr": "sum(irate(eventStore_processedCounter_total{app=\"$application\", instance=~\"$instance\"}[5m]))by(app)",
     "legendFormat": "Processed events"
    },
    {
     "expr": "sum(irate(eventStore_ingestedCounter_total{app=\"$application\", instance=~\"$instance\"}[5m]))by(app)",
     "legendFormat": "Ingested events"
    },
    {
     "expr": "sum(irate(eventStore_ignoredCounter_total{app=\"$application\", instance=\"$instance\"}[5m]))by(app)",
     "legendFormat": "Ignored events"
    }
   ]
  },
  {
   "title": "Event Bus Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(eventStore_allTimer_seconds{app=\"$application\", instance=~\"$instance\", quantile=\"0.5\"})by(app)",
     "legendFormat": "All timer (quantile=\"0.5\")"
    },
    {
     "expr": "avg(eventStore_allTimer_seconds{app=\"$application\", instance=~\"$instance\", quantile=\"0.75\"})by(app)",
     "legendFormat": "All timer (quantile=\"0.75\")"
    },
    {
     "expr": "avg(eventStore_allTimer_seconds{app=\"$application\", instance=~\"$instance\", quantile=\"0.999\"})by(app)",
     "legendFormat": "All timer (quantile=\"0.999\")"
    }
   ]
  },
  { "title": "Axon Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Success Queries",
   "type": "singlestat",
   "description": "Total number of success queries",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 33 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(queryBus_successCounter_total{app=\"$application\", instance=~\"$instance\"})by(app)"
    }
   ]
  },
  {
   "title": "Failed Queries",
   "type": "singlestat",
   "description": "Total number of failed queries",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 33 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(queryBus_failureCounter_total{app=\"$application\", instance=~\"$instance\"})by(app)"
    }
   ]
  },
  {
   "title": "Processed Queries",
   "type": "singlestat",
   "description": "Total number of processed\n queries",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 33 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(queryBus_processedCounter_total{app=\"$application\", instance=~\"$instance\"})by(app)"
    }
   ]
  },
  {
   "title": "Ingested Queeries",
   "type": "singlestat",
   "description": "Total number of ingested\n queries",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 33 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(queryBus_ingestedCounter_total{app=\"$application\", instance=~\"$instance\"})by(app)"
    }
   ]
  },
  {
   "title": "Ignored Queries",
   "type": "singlestat",
   "description": "Total number of ignored\n queries",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 33 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(queryBus_ignoredCounter_total{app=\"$application\", instance=~\"$instance\"})by(app)"
    }
   ]
  },
  {
   "title": "Queries Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "sum(irate(queryBus_successCounter_total{app=\"$application\", instance=~\"$instance\"}[5m]))by(app)",
     "legendFormat": "Success queries"
    },
    {
     "expr": "sum(irate(queryBus_failureCounter_total{app=\"$application\", instance=~\"$instance\"}[5m]))by(app)",
     "legendFormat": "Failed queries"
    },
    {
     "expr": "sum(irate(queryBus_processedCounter_total{app=\"$application\", instance=~\"$instance\"}[5m]))by(app)",
     "legendFormat": "Processed queries"
    },
    {
     "expr": "sum(irate(queryBus_ingestedCounter_total{app=\"$application\", instance=~\"$instance\"}[5m]))by(app)",
     "legendFormat": "Ingested queries"
    },
    {
     "expr": "sum(irate(queryBus_ignoredCounter_total{app=\"$application\", instance=~\"$instance\"}[5m]))by(app)",
     "legendFormat": "Ignored queries"
    }
   ]
  },
  {
   "title": "Query Bus Capacity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(queryBus_capacity{app=\"$application\", instance=~\"$instance\"})by(app)",
     "legendFormat": "Query bus"
    }
   ]
  },
  {
   "title": "Query Bus Latency",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(queryBus_allTimer_seconds{app=\"$application\", instance=~\"$instance\", quantile=\"0.5\"})by(app)",
     "legendFormat": "All timer (quantile=\"0.5\")"
    },
    {
     "expr": "avg(queryBus_allTimer_seconds{app=\"$application\", instance=~\"$instance\", quantile=\"0.75\"})by(app)",
     "legendFormat": "All timer (quantile=\"0.75\")"
    },
    {
     "expr": "avg(queryBus_allTimer_seconds{app=\"$application\", instance=~\"$instance\", quantile=\"0.999\"})by(app)",
     "legendFormat": "All timer (quantile=\"0.999\")"
    }
   ]
  }
 ]
}
{
 "title": "JVM General Statistics - Spring Boot",
 "description": "Dashboard for Spring Boot Statistics (micrometer-prometheus).",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": "label_values(app)" },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(jvm_classes_loaded_classes{app=\"$application\"}, instance)"
   },
   {
    "name": "hikaricp",
    "label": "HikariCP-Pool",
    "query": "label_values(hikaricp_connections{instance=\"$instance\", app=\"$application\"}, pool)"
   },
   {
    "name": "memory_pool_heap",
    "label": "Memory Pool (heap)",
    "query": "label_values(jvm_memory_used_bytes{app=\"$application\", instance=\"$instance\", area=\"heap\"},id)"
   },
   {
    "name": "memory_pool_nonheap",
    "label": "Memory Pool (nonheap)",
    "query": "label_values(jvm_memory_used_bytes{app=\"$application\", instance=\"$instance\", area=\"nonheap\"},id)"
   }
  ]
 },
 "panels": [
  { "title": "Basic Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_uptime_seconds{app=\"$application\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Heap Used",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{app=\"$application\", instance=\"$instance\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{app=\"$application\",instance=\"$instance\", area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Non-Heap Used",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{app=\"$application\", instance=\"$instance\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{app=\"$application\",instance=\"$instance\", area=\"nonheap\"})"
    }
   ]
  },
  {
   "title": "Process Open Files",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "process_files_open_files{app=\"$application\", instance=\"$instance\"}",
     "legendFormat": "Open Files"
    },
    {
     "expr": "process_files_max_files{app=\"$application\", instance=\"$instance\"}",
     "legendFormat": "Max Files"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_start_time_seconds{app=\"$application\", instance=\"$instance\"}*1000"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_cpu_usage{instance=\"$instance\", app=\"$application\"}",
     "legendFormat": "System CPU Usage"
    },
    {
     "expr": "process_cpu_usage{instance=\"$instance\", app=\"$application\"}",
     "legendFormat": "Process CPU Usage"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_load_average_1m{instance=\"$instance\", app=\"$application\"}",
     "legendFormat": "Load Average [1m]"
    },
    {
     "expr": "system_cpu_count{instance=\"$instance\", app=\"$application\"}",
     "legendFormat": "CPU Core Size"
    }
   ]
  },
  { "title": "JVM Statistics - Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "$memory_pool_heap (heap)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "repeat": "memory_pool_heap",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{instance=\"$instance\", app=\"$application\", id=\"$memory_pool_heap\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_committed_bytes{instance=\"$instance\", app=\"$application\", id=\"$memory_pool_heap\"}",
     "legendFormat": "Commited"
    },
    {
     "expr": "jvm_memory_max_bytes{instance=\"$instance\", app=\"$application\", id=\"$memory_pool_heap\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "$memory_pool_nonheap (non-heap)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 23 },
   "repeat": "memory_pool_nonheap",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{instance=\"$instance\", app=\"$application\", id=\"$memory_pool_nonheap\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_committed_bytes{instance=\"$instance\", app=\"$application\", id=\"$memory_pool_nonheap\"}",
     "legendFormat": "Commited"
    },
    {
     "expr": "jvm_memory_max_bytes{instance=\"$instance\", app=\"$application\", id=\"$memory_pool_nonheap\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Classes Unloaded",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(jvm_classes_unloaded_classes_total{instance=\"$instance\", app=\"$application\"}[5m])",
     "legendFormat": "Classes Unloaded"
    }
   ]
  },
  {
   "title": "Classes Loaded",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded_classes{instance=\"$instance\", app=\"$application\"}",
     "legendFormat": "Classes Loaded"
    }
   ]
  },
  {
   "title": "Mapped Buffers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{instance=\"$instance\", app=\"$application\", id=\"mapped\"}",
     "legendFormat": "Used Bytes"
    },
    {
     "expr": "jvm_buffer_total_capacity_bytes{instance=\"$instance\", app=\"$application\", id=\"mapped\"}",
     "legendFormat": "Capacity Bytes"
    }
   ]
  },
  {
   "title": "Memory Allocate/Promote",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(jvm_gc_memory_allocated_bytes_total{instance=\"$instance\", app=\"$application\"}[5m])",
     "legendFormat": "allocated"
    },
    {
     "expr": "irate(jvm_gc_memory_promoted_bytes_total{instance=\"$instance\", app=\"$application\"}[5m])",
     "legendFormat": "promoted"
    }
   ]
  },
  {
   "title": "Direct Buffers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{instance=\"$instance\", app=\"$application\", id=\"direct\"}",
     "legendFormat": "Used Bytes"
    },
    {
     "expr": "jvm_buffer_total_capacity_bytes{instance=\"$instance\", app=\"$application\", id=\"direct\"}",
     "legendFormat": "Capacity Bytes"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_daemon_threads{instance=\"$instance\", app=\"$application\"}",
     "legendFormat": "Daemon"
    },
    {
     "expr": "jvm_threads_live_threads{instance=\"$instance\", app=\"$application\"}",
     "legendFormat": "Live"
    },
    {
     "expr": "jvm_threads_peak_threads{instance=\"$instance\", app=\"$application\"}",
     "legendFormat": "Peak"
    }
   ]
  },
  { "title": "JVM Statistics - GC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "GC Count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "irate(jvm_gc_pause_seconds_count{instance=\"$instance\", app=\"$application\"}[5m])",
     "legendFormat": "{{action}} [{{cause}}]"
    }
   ]
  },
  {
   "title": "GC Stop the World Duration",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(jvm_gc_pause_seconds_sum{instance=\"$instance\", app=\"$application\"}[5m])",
     "legendFormat": "{{action}} [{{cause}}]"
    }
   ]
  },
  { "title": "HikariCP Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "Connections Size",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 74 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "hikaricp_connections{instance=\"$instance\", app=\"$application\", pool=\"$hikaricp\"}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hikaricp_connections_active{instance=\"$instance\", app=\"$application\", pool=\"$hikaricp\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "hikaricp_connections_idle{instance=\"$instance\", app=\"$application\", pool=\"$hikaricp\"}",
     "legendFormat": "Idle"
    },
    {
     "expr": "hikaricp_connections_pending{instance=\"$instance\", app=\"$application\", pool=\"$hikaricp\"}",
     "legendFormat": "Pending"
    }
   ]
  },
  {
   "title": "Connection Timeout Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 78 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "hikaricp_connections_timeout_total{instance=\"$instance\", app=\"$application\", pool=\"$hikaricp\"}"
    }
   ]
  },
  {
   "title": "Connection Creation Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "hikaricp_connections_creation_seconds_sum{instance=\"$instance\", app=\"$application\", pool=\"$hikaricp\"} / hikaricp_connections_creation_seconds_count{instance=\"$instance\", app=\"$application\", pool=\"$hikaricp\"}",
     "legendFormat": "Creation Time"
    }
   ]
  },
  {
   "title": "Connection Usage Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 82 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "hikaricp_connections_usage_seconds_sum{instance=\"$instance\", app=\"$application\", pool=\"$hikaricp\"} / hikaricp_connections_usage_seconds_count{instance=\"$instance\", app=\"$application\", pool=\"$hikaricp\"}",
     "legendFormat": "Usage Time"
    }
   ]
  },
  {
   "title": "Connection Acquire Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 82 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "hikaricp_connections_acquire_seconds_sum{instance=\"$instance\", app=\"$application\", pool=\"$hikaricp\"} / hikaricp_connections_acquire_seconds_count{instance=\"$instance\", app=\"$application\", pool=\"$hikaricp\"}",
     "legendFormat": "Acquire Time"
    }
   ]
  },
  { "title": "HTTP Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 } },
  {
   "title": "Request Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(http_server_requests_seconds_count{instance=\"$instance\", app=\"$application\", uri!~\".*actuator.*\"}[5m])",
     "legendFormat": "{{method}} [{{status}}] - {{uri}}"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(http_server_requests_seconds_sum{instance=\"$instance\", app=\"$application\", exception=\"None\", uri!~\".*actuator.*\"}[5m]) / irate(http_server_requests_seconds_count{instance=\"$instance\", app=\"$application\", exception=\"None\", uri!~\".*actuator.*\"}[5m])",
     "legendFormat": "{{method}} [{{status}}] - {{uri}}"
    }
   ]
  },
  { "title": "Logback Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 103 } },
  {
   "title": "INFO logs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 104 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(logback_events_total{instance=\"$instance\", app=\"$application\", level=\"info\"}[5m])",
     "legendFormat": "info",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "ERROR logs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 104 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(logback_events_total{instance=\"$instance\", app=\"$application\", level=\"error\"}[5m])",
     "legendFormat": "error",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "WARN logs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 111 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(logback_events_total{instance=\"$instance\", app=\"$application\", level=\"warn\"}[5m])",
     "legendFormat": "warn",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "DEBUG logs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 111 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(logback_events_total{instance=\"$instance\", app=\"$application\", level=\"debug\"}[5m])",
     "legendFormat": "debug",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "TRACE logs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 111 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(logback_events_total{instance=\"$instance\", app=\"$application\", level=\"trace\"}[5m])",
     "legendFormat": "trace",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  }
 ]
}